In [1]:
import os, glob
import pickle
import numpy as np
import pandas as pd

from astropy.io import fits
from astropy.table import Table

In [2]:
channels = np.delete(np.arange(1, 85), [4,5,6,7])
quarters = np.arange(5, 18)

In [188]:
rknots = {}
phiknots = {}
df_dict = {}

for q in quarters:
    quarter_table = []
    for ch in channels:
        fname = "../data/models/%i/channel_%02i_psf_model.pkl" % (
                    q,
                    ch,
                )
        if os.path.isfile(fname):
            psf = pickle.load(open(fname, "rb"))
        
        rknots["q%i_ch%i" % (q, ch)]   = psf["n_r_knots"]
        phiknots["q%i_ch%i" % (q, ch)] = psf["n_phi_knots"]
        
        quarter_table.append([psf["n_r_knots"], psf["n_phi_knots"], psf["rmin"], psf["rmax"]] + psf["psf_w"].tolist())
    aux = pd.DataFrame(np.array(quarter_table), index=channels,
                       columns=["n_r_knots", "n_phi_knots", "rmin", "rmax"] + ["b%02i" % i for i in range(1, 1 + len(psf["psf_w"]))],
                      )
    df_dict[q] = aux.astype({"n_r_knots": int, "n_phi_knots": int})

In [189]:
df_dict[9]

n_r_knots  n_phi_knots  rmin      rmax       b01       b02       b03  \
1           5           15  0.25  3.364680 -7.759541 -7.795999 -8.000449   
2           5           15  0.25  3.250000 -7.880535 -7.863690 -7.844513   
3           5           15  0.25  4.084838 -7.852863 -7.757303 -7.999418   
4           5           15  0.25  4.375038 -7.702546 -7.832952 -7.563741   
9           5           15  0.25  2.813566 -7.969017 -7.896278 -7.832677   
..        ...          ...   ...       ...       ...       ...       ...   
80          5           15  0.25  3.277399 -7.658009 -7.682627 -7.777021   
81          5           15  0.25  3.162728 -7.589567 -7.589573 -7.877459   
82          5           15  0.25  2.768972 -7.883044 -7.758320 -7.658383   
83          5           15  0.25  3.379004 -7.906214 -7.597245 -7.633641   
84          5           15  0.25  3.854847 -7.506247 -7.621311 -7.766218   

         b04       b05       b06  ...        b85        b86        b87  \
1  -7.987204 -7.970165 -7.695676  ... -11.490091 -11.444232 -10.753712   
2  -7.799445 -7.780850 -7.841380  ... -11.552842 -11.661390 -11.276530   
3  -7.900163 -7.872826 -7.896340  ... -10.977402 -10.009438 -11.559807   
4  -7.726647 -7.782772 -7.701845  ... -10.185350 -12.931566 -11.229571   
9  -7.655496 -7.573522 -7.569144  ... -11.183254 -11.467420 -11.506072   
..       ...       ...       ...  ...        ...        ...        ...   
80 -7.714168 -7.964023 -8.041758  ...  -9.985338 -11.536022 -11.520542   
81 -8.066432 -8.185106 -8.232624  ... -11.239022 -11.427702 -11.230709   
82 -7.456440 -7.502524 -7.552613  ... -11.004118 -11.729965 -11.274297   
83 -7.588495 -7.462902 -7.533803  ... -11.159580 -10.028772 -10.909763   
84 -8.120758 -8.190631 -8.366927  ... -10.657242 -12.115193 -11.544068   

          b88        b89        b90       b91       b92       b93       b94  
1  -11.878643 -11.155335 -11.788102 -7.662163 -7.620266 -7.698197  7.075895  
2  -12.605935 -10.702675 -12.166311 -7.693497 -7.723076 -7.722136  7.087107  
3  -12.398119 -11.070485 -11.949950 -7.810121 -7.841585 -7.830336  7.110596  
4  -11.792870 -11.646448 -11.701721 -7.835502 -7.780451 -7.880232  7.111109  
9  -11.093343 -11.513954 -12.108115 -7.439417 -7.414753 -7.497325  7.018756  
..        ...        ...        ...       ...       ...       ...       ...  
80 -11.359103 -11.242896 -11.829507 -7.677105 -7.639225 -7.716950  7.095485  
81 -12.276063 -10.589865 -12.829520 -7.653195 -7.529665 -7.719115  7.099636  
82 -10.665777 -11.381831 -11.858108 -7.487419 -7.392810 -7.521219  7.038163  
83 -11.968228 -11.312558 -11.080877 -7.619498 -7.518261 -7.653734  7.077649  
84 -12.093025 -11.713144 -11.875292 -7.740979 -7.660428 -7.788788  7.099919  

[80 rows x 98 columns]

In [228]:
big_df = pd.concat(df_dict, axis=1, keys=df_dict.keys())

In [241]:
big_df.iloc[0]

5   n_r_knots       5.000000
    n_phi_knots    15.000000
    rmin            0.250000
    rmax            3.376794
    b01            -7.765737
                     ...    
17  b97            -8.056316
    b98            -8.395562
    b99             6.784707
4   n_r_knots            NaN
3                        NaN
Name: 1, Length: 1286, dtype: float64

In [239]:
big_df.loc[4, (3)] =  np.ones(df_dict[9].shape[1])

ValueError: Must have equal len keys and value when setting with an iterable

In [235]:
big_df

5                                                             \
   n_r_knots n_phi_knots  rmin      rmax       b01       b02       b03   
1        5.0        15.0  0.25  3.376794 -7.765737 -7.784850 -7.991183   
2        5.0        15.0  0.25  3.239576 -7.857621 -7.845904 -7.826212   
3        5.0        15.0  0.25  4.072613 -7.856318 -7.744335 -7.986249   
4        5.0        15.0  0.25  4.370507 -7.691236 -7.823086 -7.551946   
9        5.0        15.0  0.25  2.814273 -7.958479 -7.900866 -7.834391   
..       ...         ...   ...       ...       ...       ...       ...   
81       5.0        15.0  0.25  3.176469 -7.590662 -7.598381 -7.867759   
82       5.0        15.0  0.25  2.786804 -7.883146 -7.764053 -7.656907   
83       5.0        15.0  0.25  3.341721 -7.905853 -7.600340 -7.629986   
84       5.0        15.0  0.25  3.824362 -7.518385 -7.627133 -7.780048   
5        1.0         1.0  1.00  1.000000  1.000000  1.000000  1.000000   

                                  ...        17                                \
         b04       b05       b06  ...       b91       b92       b93       b94   
1  -7.971245 -7.962780 -7.680903  ... -7.360662 -7.363866 -7.395490 -7.457543   
2  -7.787396 -7.768033 -7.832767  ... -7.426328 -7.407254 -7.439555 -7.482587   
3  -7.881471 -7.865965 -7.882475  ... -7.590194 -7.604584 -7.605100 -7.686175   
4  -7.736333 -7.776276 -7.710599  ... -7.582023 -7.582416 -7.617988 -7.692464   
9  -7.655144 -7.578270 -7.566412  ... -7.094574 -7.099963 -7.141102 -7.232658   
..       ...       ...       ...  ...       ...       ...       ...       ...   
81 -8.065727 -8.168777 -8.232219  ... -7.249624 -7.248130 -7.293681 -7.389222   
82 -7.457165 -7.495201 -7.550572  ... -7.115666 -7.095333 -7.136745 -7.234269   
83 -7.584570 -7.448121 -7.534362  ... -7.248303 -7.263935 -7.279002 -7.387372   
84 -8.130048 -8.189597 -8.373253  ... -7.433347 -7.427313 -7.471893 -7.561085   
5   1.000000  1.000000  1.000000  ...       NaN       NaN       NaN       NaN   

                                                            4   
         b95       b96       b97       b98       b99 n_r_knots  
1  -7.590775 -7.779278 -8.056316 -8.395562  6.784707       NaN  
2  -7.599979 -7.757258 -7.984155 -8.294801  6.782425       NaN  
3  -7.764524 -7.907010 -8.123311 -8.404154  6.854371       NaN  
4  -7.776891 -7.904208 -8.148766 -8.465687  6.855378       NaN  
9  -7.403615 -7.655586 -8.038722 -8.458815  6.676794       NaN  
..       ...       ...       ...       ...       ...       ...  
81 -7.534121 -7.729073 -8.048592 -8.466147  6.745246       NaN  
82 -7.407670 -7.657786 -8.056353 -8.511114  6.691314       NaN  
83 -7.531269 -7.754849 -8.070114 -8.476676  6.763155       NaN  
84 -7.666691 -7.857081 -8.110947 -8.493945  6.832634       NaN  
5        NaN       NaN       NaN       NaN       NaN       5.0  

[81 rows x 1285 columns]

In [230]:
big_df.to_csv("../res/ffi_prf_models_v0.1.csv")

In [195]:
aux = pd.read_csv("../res/ffi_prf_models_v0.1.csv", index_col=0, header=[0, 1])

In [203]:
aux.loc[4, str(7)].iloc[4:].values

array([ -7.81940067,  -7.94431504,  -7.64343653,  -7.77246111,
        -7.84626747,  -7.7559352 ,  -8.38717976,  -8.63992375,
        -8.97317348,  -8.96094148,  -8.55050443,  -8.29926281,
        -7.87177736,  -7.81581084,  -7.902444  ,  -8.89291264,
        -8.78563005,  -8.56853791,  -8.05935812,  -8.03939667,
        -9.12037333,  -8.64240145,  -8.89730375,  -9.16202765,
        -8.78923724,  -8.83095105,  -8.80509128,  -8.64142676,
        -8.42008706,  -8.19403098,  -9.10407796,  -8.99889702,
        -8.57871412, -10.06131701, -10.47193567, -10.42302404,
        -9.49954001,  -8.71645981,  -9.40240922,  -8.65076511,
        -9.28262456, -10.03292415,  -9.72698601,  -9.90314756,
        -8.73334446, -10.31836805, -10.12658289, -10.73041362,
       -11.2221447 , -10.12840407, -10.14130826, -11.27989665,
        -9.24150583,  -9.3109905 ,  -9.09959608, -10.59162935,
       -10.81131496, -10.68175108, -10.91187614,  -9.81563735,
       -11.5475737 , -11.74685374, -11.71643842, -10.70

In [62]:
primary_hdu = fits.PrimaryHDU(data=None)
phdr = primary_hdu.header
phdr.set("OBJECT", "PRF models")
phdr.set("EXTNAME", "PRIMARY")

In [63]:
table_hdus = []
for q in df_dict.keys():
    cols = []
    for col in df_dict[q].columns:
        column = fits.Column(name="ch%02i" % int(df_dict[q].loc["channel", col]), format="D", array=df_dict[q].loc[:,col][1:])
        cols.append(column)
    coldef = fits.ColDefs(cols)
    hdu = fits.BinTableHDU.from_columns(coldef)
    hdu.header["EXTNAME"] = "QUARTER_%02i" % q
    hdu.header["QUARTER"] = q
    hdu.header["ROW0"] = "n_r_knots"
    hdu.header["ROW1"] = "n_phi_knots"
    hdu.header["ROW2"] = "rmin"
    hdu.header["ROW3"] = "rmax"
    hdu.header["ROW4"] = "prf_w"
    table_hdus.append(hdu)

In [64]:
hdul = fits.HDUList([primary_hdu] + table_hdus)

In [65]:
hdul.info()

Filename: (No file associated with this HDUList)
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   ()      
  1  QUARTER_05    1 BinTableHDU    175   98R x 80C   ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D']   
  2  QUARTER_06    1 BinTableHDU    175   98R x 80C   ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 

In [9]:
hdul["QUARTER_17"].data["ch01"]

array([ 10.        ,  15.        ,   0.25      ,   3.34944001,
        -9.65616597,  -9.8651296 ,  -8.24865238,  -8.18700085,
        -8.18553363,  -9.23433649, -10.38318305,  -9.24229113,
        -9.50721813,  -8.20332069,  -8.17174694,  -8.74614682,
        -7.84488237,  -9.07003846,  -8.81985796,  -9.71935483,
        -9.43534928,  -8.91788435,  -8.57509776,  -8.80054023,
        -9.44285737,  -9.66129473, -10.02671357,  -9.87492812,
        -8.93876836,  -8.51929102,  -8.83935422,  -8.55309058,
        -9.47883881,  -9.23887732, -10.44140103, -10.39304029,
        -9.00952893,  -8.74364453,  -8.86712191,  -9.94016572,
       -10.80950536,  -9.97056623, -10.53070836,  -9.08989177,
        -8.69007006,  -9.15417088,  -8.6051838 ,  -9.95866322,
        -9.76027165, -10.63910315, -11.06611505,  -9.79287466,
        -9.46113246,  -9.66688324, -10.85051859, -10.37930155,
       -11.34301894, -11.12521993, -10.25532393,  -9.48931529,
        -9.79839499,  -9.64486708, -10.62052557, -10.96

In [10]:
test = fits.open("../res/ffi_prf_models_v0.1.fits")

In [24]:
ch52 = test["QUARTER_09"].data["ch52"]

In [25]:
ch52

array([  5.        ,  15.        ,   0.25      ,   3.42840196,
        -7.41775269,  -7.55461348,  -7.48155595,  -7.6011469 ,
        -7.95695156,  -7.98228577,  -8.15279119,  -8.15499765,
        -8.27163028,  -8.29511474,  -8.32869499,  -8.07837953,
        -7.90838007,  -7.82818406,  -7.68952478,  -8.68652703,
        -8.61038002,  -8.8393944 ,  -8.72781499,  -8.36548847,
        -8.35182124,  -8.7340669 ,  -9.27363258,  -8.71630834,
        -8.53198369,  -8.5009471 ,  -9.2823208 ,  -8.99020668,
        -8.46464909,  -8.58359503, -10.22014056,  -9.99202724,
        -9.65239549, -10.36008257,  -9.61203343,  -8.47408754,
        -9.40814324,  -9.95239269,  -9.2020001 ,  -8.72210846,
        -9.04145241,  -9.99700848,  -9.73220683,  -8.71826436,
        -9.65821012, -10.10296277, -10.44699225, -11.05226185,
        -9.73914018, -11.68679121,  -9.48290501, -10.73535187,
       -10.97322142,  -9.95073931,  -9.11717976,  -9.9738848 ,
       -11.29164493, -10.79121203,  -9.96523345, -11.46

In [177]:
test["QUARTER_05"].data[1][0]

15.0

In [136]:
old_columns = test["QUARTER_05"].data.columns.add_col(column)

In [143]:
table = Table(test["QUARTER_05"].data)

In [161]:
column.array

array([ 10.        ,  15.        ,   0.25      ,   3.77327639,
        -8.85913148,  -8.71589134,  -9.13078959,  -8.50138393,
        -7.89768136,  -9.24457872,  -9.64762842,  -8.44668701,
        -8.73545193,  -8.42774469,  -9.30070418,  -9.57947171,
        -8.60852197,  -9.07565625,  -9.22649352,  -9.56972821,
        -9.16189203,  -9.58297966,  -9.27772794,  -8.3713333 ,
        -9.27108154,  -9.38407082,  -8.72446364,  -8.76232246,
        -8.65673895,  -9.3773321 ,  -9.71104088,  -9.20066023,
        -9.59944797,  -9.57972652, -10.0214277 ,  -9.61114705,
        -9.87126692,  -9.79730609,  -8.15555231,  -9.91685849,
       -10.20943483,  -8.79915995,  -8.92934292,  -8.77051042,
       -10.18330489, -10.03674941,  -9.74287085, -10.01912902,
        -9.86114289, -10.55263193, -10.79520925, -10.23937112,
       -10.99079797,  -9.2959426 , -10.47570682, -10.59673623,
        -9.44686199,  -9.1284481 ,  -9.36692238, -11.00189111,
       -10.56760116, -10.80608802, -10.70924355, -10.89

In [158]:
table.add_column(column.array, name=column.name)

ValueError: Inconsistent data column lengths

In [36]:
test2 = fits.open("../res/prf_test.fits")

In [37]:
test2.info()

Filename: ../res/prf_test.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  Quarter number    1 PrimaryHDU       6   ()      
  1  QUARTER_15    1 BinTableHDU     17   98R x 1C   [D]   


In [48]:
test2["QUARTER_11"].data["ch84"]

KeyError: "Extension 'QUARTER_11' not found."

In [35]:
test2.writeto("../res/prf_test.fits", overwrite=True)

In [55]:
test2.append(test[1])

In [59]:
test2.info()

Filename: ../res/prf_test.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  Quarter number    1 PrimaryHDU       6   ()      
  1  QUARTER_15    1 BinTableHDU     17   98R x 1C   ['D']   
  2  QUARTER_05    1 BinTableHDU    175   98R x 80C   [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D]   
  3  QUARTER_05    1 BinTableHDU    175   98R x 80C   [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D]   
  4  QUARTER_05    1 BinTableHDU    175   98R x 80C   [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D

In [58]:
[hdu["EXTNAME"] for hdu in test2]

TypeError: 'PrimaryHDU' object is not subscriptable

In [46]:
test2.__dir__()

['_file',
 '_data',
 '_open_kwargs',
 '_in_read_next_hdu',
 '_read_all',
 '_resize',
 '_truncate',
 '__module__',
 '__doc__',
 '__init__',
 '__len__',
 '__repr__',
 '__iter__',
 '__getitem__',
 '__contains__',
 '__setitem__',
 '__delitem__',
 '__enter__',
 '__exit__',
 'fromfile',
 'fromstring',
 'fileinfo',
 '__copy__',
 'copy',
 '__deepcopy__',
 'pop',
 'insert',
 'append',
 'index_of',
 '_positive_index_of',
 'readall',
 'flush',
 'update_extend',
 'writeto',
 'close',
 'info',
 'filename',
 '_readfrom',
 '_try_while_unread_hdus',
 '_read_next_hdu',
 '_verify',
 '_flush_update',
 '_flush_resize',
 '_wasresized',
 '__dict__',
 '__weakref__',
 '__hash__',
 '__getattribute__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__add__',
 '__mul__',
 '__rmul__',
 '__iadd__',
 '__imul__',
 '__new__',
 '__reversed__',
 '__sizeof__',
 'clear',
 'extend',
 'remove',
 'index',
 'count',
 'reverse',
 'sort',
 '__str__',
 '__setattr__',
 '__delattr__',
 '__reduce_ex__',
 '__re